### ISSUE TITLE
Using filterer without pagination

### ISSUE THREAD

**Issue by ramontayag** [dobtco/filterer#13]
I like the way filterer makes it easy to pass params and get the result without having a bunch of `if`s. However, I don't always use it for an API -- sometimes I use it in some service object to allow fellow developers pass in options that are in turn used in the filterer object. The problem is that I don't want pagination for this. Is there a way to use filterer without pagination?

**Comment by ajb** [comment]
Yup -- use `filterer.chain`:

```rb
filterer.chain(params_hash).now_do_whatever_method_to_your_collection
```

**Comment by ramontayag** [comment]
Ah didn't know this. Thanks!
