### ISSUE TITLE
per_page causing error where string is compared to fixnum

### ISSUE THREAD

**Issue by ramontayag** [dobtco/filterer#19]
This happens because `per_page`, when given in the params, is a string. I have a branch that fixes it [here](https://github.com/G5/filterer/tree/per_page_string_fix). I didn't create a pull request because there's no "0_4_x" branch to merge it into. Note: this branch is from `v0.4.2`. I took a quick look at master and I think master is susceptible to this issue too.

**Comment by ajb** [comment]
Thanks! I released 0.4.3 with a fix, as well as fixing in `master`.
